version: '3'

services:
  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=\[\"apoc\"\]
    volumes:
      - neo4j_data:/conf
      - neo4j_data:/data
      - neo4j_data:/plugins
#     - neo4j_data:/logs
      - ~/neo4j/logs:/logs
      - ~/neo4j/import:/var/lib/neo4j/import

volumes:
  neo4j_data:
